# This is the configuration, I've put on the board.
# If you apply voltage to it, the green LED D! serves as status led2
# usually blinking with around 1 Hz. If you press button USER 1, it will
# toggle green led D2.
# To upload a new firmware, search for the "Fallback Hotspot" WiFi and
# log in with password "Z8zfajgxVvNw". It could take up to a minute for
# the fallack AP to be enabled when not able to connect to the "test"
# wifi network. So, if status is blinking, give it a minute to show up.
substitutions:
  name: "km271-for-friends"

esphome:
  name: "${name}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  platformio_options:
    upload_speed: 921600
    #board_build.f_flash: 80000000L
    #board_build.partitions: "default_8MB.csv
    #upload_flash_size: "8MB"

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: the78mole.km271-wifi
    version: "1.0"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
#  password: "xxx"

wifi:
#  ssid: "test"
#  password: "testtest"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "KM271 Fallback Hotspot"
    password: ""

dashboard_import:
  package_import_url: github://jmilljr24/esphome_components/components/km271_wifi/km271-for-friends.yaml@main

captive_portal:
#  keep_user_credentials: true

uart:
  id: uart_bus
  tx_pin: GPIO2
  rx_pin: GPIO4
  baud_rate: 2400

external_components:
  - source: github://the78mole/esphome_components@main
    components: [ km271_wifi ]
    refresh:    1sec
#  - source:
#    type: local
#      path: my_components/components
#    components: [ km271_wifi ]


#esp32_improv:
#  authorizer: improvble
#  authorized_duration: 120s
#  status_indicator: led3
#  identify_duration: 60s

#improv_serial:


status_led:
  id: ledgn1
  pin:
    number: GPIO21
    inverted: true

km271_wifi:
  - id: budoil
    uart_id: uart_bus

binary_sensor:
  - platform: gpio
    id: improvble
    name: "USER 2"
    pin:
      number: GPIO27
      inverted: true
      mode:
        input: true
        pullup: true

# Above is all the "give-away hardware suggestion stuff"
# It is the place for cleanup of to reduce flash footprint, like:
# improv, captive portal, dashboard_import,...)
##################################################################

##################################################################
# Below is the real example stuff

  - platform: km271_wifi
    # Betriebswerte 1 HK1
   heating_circuit_1_switch_off_optimization:
     name: "HC1 Swith Off Optimization "
   heating_circuit_1_switch_on_optimization:
     name: "HC1 Switch On Optimization"
   heating_circuit_1_automatic:
     name: "HC1 Automatic"
   heating_circuit_1_ww_priority_processing:
     name: "HC1 Hot Water Priority Processing"
   heating_circuit_1_screed_drying:
     name: "HC1 Screed Drying"
   heating_circuit_1_holiday:
     name: "HC1 Holiday"
   heating_circuit_1_antifreeze:
     name: "HC1 Antifreeze"
   heating_circuit_1_manually:
     name: "HC1 Manual"
   # Betriebswerte 2 HK1
   heating_circuit_1_summer:
     name: "HC1 Summer Mode"
   heating_circuit_1_day:
     name: "HC1 Day Mode"
   heating_circuit_1_no_comm_with_rc:
     name: "HC1 No Communication with RC"
   heating_circuit_1_rc_faulty:
     name: "HC1 RC Faulty"
   heating_circuit_1_flow_sensor_error:
     name: "HC1 Flow Sensor Error"
   heating_circuit_1_max_flow:
     name: "HC1 Max Flow"
   heating_circuit_1_external_fault_input:
     name: "HC1 External Fault Input"
   # Betriebswerte 1 HK2
   heating_circuit_2_switch_off_optimization:
     name: "HC2 Swith Off Optimization"
   heating_circuit_2_switch_on_optimization:
     name: "HC2 Switch On Optimization"
   heating_circuit_2_automatic:
     name: "HC2 Automatic"
   heating_circuit_2_ww_priority_processing:
     name: "HC2 Hot Water Priority Proccessing"
   heating_circuit_2_screed_drying:
     name: "HC2 Screed Drying"
   heating_circuit_2_holiday:
     name: "HC2 Holiday"
   heating_circuit_2_antifreeze:
     name: "HC2 Antifreeze"
   heating_circuit_2_manually:
     name: "HC2 Manual"
   # Betriebswerte 2 HK2
   heating_circuit_2_summer:
     name: "HC2 Summer Mode"
   heating_circuit_2_day:
     name: "HC2 Day Mode"
   heating_circuit_2_no_comm_with_rc:
     name: "HC2 No Communication with RC"
   heating_circuit_2_rc_faulty:
     name: "HC2 RC Faulty"
   heating_circuit_2_flow_sensor_error:
     name: "HC2 Flow Sensor Error"
   heating_circuit_2_max_flow:
     name: "HC2 Max Flow"
   heating_circuit_2_external_fault_input:
     name: "HC2 External Fault Input"
   # Betriebswerte 1 WW
   ww_automatic:
     name: "Hot Water Automatic"
   ww_disinfection:
     name: "Hot Water Disinfection"
   ww_reload:
     name: "Hot Water Reload"
   ww_holiday:
     name: "Hot Water Holiday"
   ww_error_disinfection:
     name: "Hot Water Error Disinfection"
   ww_error_sensor:
     name: "Hot Water Error Sensor"
   ww_error_stays_cold:
     name: "Hot Water Error Stays Cold"
   ww_error_anode:
     name: "Hot Water Error Anode"
   # Betriebswerte 2 WW
   ww_loading:
     name: "Hot Water Loading"
   ww_manually:
     name: "Hot Water Manual"
   ww_reloading:
     name: "Hot Water Reloading"
   ww_switch_off_optimization:
     name: "Hot Water Switch Off Optimization"
   ww_switch_on_optimization:
     name: "Hot Water Switch On Optimization"
   ww_day_mode:
     name: "Hot Water Day Mode"
   ww_post_processing:
     name: "Hot Water Post Processing"
   ww_priority_processing:
     name: "Hot Water Priority Processing"
   # Kesselfehler
   error_burner_malfunction:
     name: "Error Burner Malfunction"
   error_boiler_sensor:
     name: "Error Boiler Sensor"
   error_additional_sensor:
     name: "Error Additional Sensor"
   error_boiler_stays_cold:
     name: "Error Boiler Stays Cold"
   error_exhaust_gas_sensor:
     name: "Error Exhaust Gas Sensor"
   error_exhaust_gas_over_limit:
     name: "Error Exhaust Gas Over Limit"
   error_safety_chain_released:
     name: "Error Saftey Chain Released"
   error_external_disturbance:
     name: "Error External Disturbance"
   # Kesselbetrieb
   boiler_emission_test:
     name: "Boiler Emission Test"
   boiler_1st_stage_operation:
     name: "Boiler 1st Stage Operation"
   boiler_protection:
     name: "Boiler Protection"
   boiler_under_operation:
     name: "Boiler Under Operation"
   boiler_performance_free:
     name: "Boiler Performace Free"
   boiler_performance_high:
     name: "Boiler Performace High"
   boiler_2st_stage_operation:
     name: "Boiler 2nd Stage Operation"
   boiler_actuation:
     name: "Boiler Actuation"
 #Alarmstatus
   alarm_exhaust_gas_sensor:
     name: "Alarm Exhaust Gas Sensor"
   alarm_boiler_flow_sensor:
     name: "Alarm Boiler Flow Sensor"
   alarm_burner:
     name: "Alarm Burner"
   alarm_heating_circuit_2_flow_sensor:
     name: "Alarm HC2 Flow Sensor"
 #Other stuff
   load_pump_running:
     name: "Load Pump Running"
   circulation_pump_running:
     name: "Circulation Pump Runnin g"
   solar_pump_lowering:
     name: "Solar Pump Lowering"



output:
  - platform: gpio
    id: led3
    #name: LED3_Yellow
    pin:
      number: 23
      mode: OUTPUT
      inverted: true
  - platform: gpio
    id: led4
    #name: LED4_Red
    pin:
      number: 25
      mode: OUTPUT
      inverted: true

button:
  - platform: restart
    name: "KM271-WiFi Restart"
# Some older Example for sending raw telegrams, replaced by a select
#  - platform: template
#    name: "KM271 WW-Bereitung Aus"
#    on_press:
#      - lambda:
#          uint8_t command[] = {0x0C, 0x0E, 0x00, 0x65, 0x65, 0x65, 0x65, 0x65};
#          budoil->writer.enqueueTelegram(command, 8);
#  - platform: template
#    name: "KM271 WW-Bereitung Ein"
#    on_press:
#      - lambda:
#          uint8_t command[] = {0x0C, 0x0E, 0x01, 0x65, 0x65, 0x65, 0x65, 0x65};
#          budoil->writer.enqueueTelegram(command, 8);
#  - platform: template
#    name: "KM271 WW-Bereitung Auto"
#    on_press:
#      - lambda:
#          uint8_t command[] = {0x0C, 0x0E, 0x02, 0x65, 0x65, 0x65, 0x65, 0x65};
#          budoil->writer.enqueueTelegram(command, 8);


number:
  - platform: km271_wifi
   config_ww_temperature:
     name: "Hot Water Temperature Day"
     mode: slider
   config_frost_switch_temperature:
     name: "Frost Changover Temperature"
     mode: slider

   config_heating_circuit_1_room_target_temperature_night:
     name: "Heating Circuit 1 Target Temperature Night"
     mode: slider
   config_heating_circuit_1_room_target_temperature_day:
     name: "Heating Circuit 1 Target Temperature Day"
     mode: slider
   config_heating_circuit_1_holiday_target_temperature:
     name: "Holiday Temperature"
     mode: slider
   config_heating_circuit_1_flow_temperature_max:
     name: "Heating Circuit 1 Max Flow Temperature"
     mode: slider
   config_heating_circuit_1_design_temperature:
     name: "Heating Circuit 1 Design Temperature"
     mode: slider
   config_heating_circuit_1_room_temperature_offset:
     name: "Heating Circuit 1 Room Temperature Offset"
     mode: slider
   config_heating_circuit_1_holiday_days:
     name: "Heating Circuit 1 Holiday Days"
     mode: slider

   config_heating_circuit_2_room_target_temperature_night:
     name: "Heating Circuit 2 Target Temperature Night"
     mode: slider
   config_heating_circuit_2_room_target_temperature_day:
     name: "Heating Circuit 2 Target Temperature Day"
     mode: slider
   config_heating_circuit_2_holiday_target_temperature:
     name: "Holiday Temperature"
     mode: slider
   config_heating_circuit_2_flow_temperature_max:
     name: "Heating Circuit 2 Max Flow Temperature"
     mode: slider
   config_heating_circuit_2_design_temperature:
     name: "Heating Circuit 2 Design Temperature"
     mode: slider
   config_heating_circuit_2_room_temperature_offset:
     name: "Heating Circuit 2 Room Temperature Offset"
     mode: slider
   config_heating_circuit_2_holiday_days:
     name: "Heating Circuit 2 Holiday Days"
     mode: slider

select:
  - platform: km271_wifi
   config_ww_operation_mode:
     name: "Hot Water Operation Mode"
   config_ww_circular_pump_interval:
     name: "Hot Water Circulation Pump Interval"

   config_heating_circuit_1_summer_winter_switch_temperature:
     name: "HC1 Summer Winter Switch Temperature"
   config_heating_circuit_1_operation_mode:
     name: "HC1 Operation Mode"
   config_heating_circuit_1_lowering_type:
     name: "HC1 Lowering Type"
   config_heating_circuit_1_heating_system_type:
     name: "HC1 Heating System Type"
   config_heating_circuit_1_heating_program:
     name: "HC1 Heating Program"

   config_heating_circuit_2_summer_winter_switch_temperature:
     name: "HC2 Summer Winter Switch"
   config_heating_circuit_2_operation_mode:
     name: "HC2 Operation Mode"
   config_heating_circuit_2_lowering_type:
     name: "HC2 Lowering Type"
   config_heating_circuit_2_heating_system_type:
     name: "HC2 Heating System Type"
   config_heating_circuit_2_heating_program:
     name: "HC2 Heating Program"


sensor:
  - platform: km271_wifi
   heating_circuit_1_flow_target_temperature:
     name: "HC1 Flow Target Temperature"
   heating_circuit_1_flow_temperature:
     name: "HC1 Flow Temperature"
   heating_circuit_1_room_target_temperature:
     name: "HC1 Room Target Temperature"
   heating_circuit_1_room_temperature:
     name: "HC1 Room Temperature"
   heating_circuit_1_pump_power:
     name: "HC1 Pump Power"
   heating_circuit_1_mixer_position:
     name: "HC1 Mixer Position"
   heating_circuit_1_curve_p10:
     name: "HK1 Heizkurve +10 °C"
   heating_circuit_1_curve_0:
     name: "HC1 Curve 0 °C"
   heating_circuit_1_curve_n10:
     name: "HC1 Curve -10 °C"
   heating_circuit_2_flow_target_temperature:
     name: "HC2 Flow Target Temperature"
   heating_circuit_2_flow_temperature:
     name: "HC2 Flow Temperature"
   heating_circuit_2_room_target_temperature:
     name: "HC2 Room Target Temperature"
   heating_circuit_2_room_temperature:
     name: "HC2 Room Temperature"
   heating_circuit_2_pump_power:
     name: "HC2 Pumper Power"
   heating_circuit_2_mixer_position:
     name: "HC2 Mixer Position"
   heating_circuit_2_curve_p10:
     name: "HC2 Curve +10 °C"
   heating_circuit_2_curve_0:
     name: "HC2 Curve 0 °C"
   heating_circuit_2_curve_n10:
     name: "HC2 Curve -10 °C"
   ww_target_temperature:
     name: "Hot Water Target Temperature"
   ww_temperature:
     name: "Hot Water Temperature"
   boiler_target_temperature:
     name: "Boiler Target Temperature"
   boiler_temperature:
     name: "Boiler Temperature"
   boiler_turn_on_temperature:
     name: "Boiler Turn On Temperature"
   boiler_turn_off_temperature:
     name: "Boiler Turn Off Temperature"
   exhaust_gas_temperature:
     name: "Exhaust Gas Temperature"
   outdoor_temperature:
     name: "Outdoor Temperature"
   attenuated_outdoor_temperature:
     name: "Dampened Outside Temperature"
   boiler_runtime_1:
     name: "Boiler Runtime 1"
   boiler_runtime_2:
     name: "Boiler Runtime 2"


  - platform: wifi_signal
    name: "KM217 WiFi Signal Sensor"
    update_interval: 60s

  - platform: adc
    pin: 36
    unit_of_measurement: "V"
    name: "KM217 5V Supply"
    accuracy_decimals: 2
    update_interval: 5s
    attenuation: 6dB
    filters:
      - multiply: 28.1826
      - throttle_average: 60s

switch:
  - platform: gpio
    name: LED2_Green
    pin:
      number: 22
      mode: OUTPUT
      inverted: true

text_sensor:
  - platform: km271_wifi
    firmware_version:
      name: "Firmware Version"
